# The URL the site will be built for
base_url = "https://misaim.github.io/side-launch/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Output Dir for Github Pages
output_dir = "public"

# Theme is hook. https://github.com/InputUsername/zola-hook
theme = "hook"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
links = [
    #{ title = "Link display text", href = "http://example.com" },
    # ...
]

users = [
    {name = "Asjad", href="asjad"},
    {name = "Jack", href="jack"},
    {name = "Liam", href="liam"},
]